# Generated by Django 4.0.4 on 2022-06-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(default=' ', max_length=420),
        ),
    ]
